language: node_js
node_js:
  - 16
services:
  - docker

# pre-testing installs
install:
  - echo "nothing needs to be installed"

# scripts to be run such as tests
before_scripts:
  - echo "no tests"

script: 
  - docker --version
  - docker build -t simple-node .
  - docker tag sample-node kibrom/sample_node_uda_00

after_sucess:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kibrom/sample_node_uda_00

