language: node_js
node_js:
  - 16
services:
  - docker

# pre-testing installs
install:
  - echo "nothing needs to be installed"

# scripts to be run such as tests
before_scripts:
  - echo "no tests"

script: 
  - docker --version
  - docker build -t simple-node .
  - docker tag simple-node kibrom/simple-node:latest

after_sucess:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kibrom/simple-node

